controller_manager:
  ros__parameters:
    update_rate: 600  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    io_and_status_controller:
      type: ur_controllers/GPIOController

    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    force_torque_sensor_broadcaster:
      type: ur_controllers/ForceTorqueStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    velocity_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0


force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: tool0
    topic_name: ft_data


joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0


scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0

forward_velocity_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    interface_name: velocity

velocity_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
      shoulder_pan_joint:
        goal: 0.05
        trajectory: 0.05
      shoulder_lift_joint:
        goal: 0.05
        trajectory: 0.05
      elbow_joint:
        goal: 0.05
        trajectory: 0.05
      wrist_1_joint:
        goal: 0.05
        trajectory: 0.05
      wrist_2_joint:
        goal: 0.05
        trajectory: 0.05
      wrist_3_joint:
        goal: 0.05
        trajectory: 0.05
    gains:
      shoulder_pan_joint: {p: 50.0, d: 0.0, i: 0.1, i_clamp: 0.5}
      shoulder_lift_joint: {p: 50.0, d: 0.0, i: 0.1, i_clamp: 0.5}
      elbow_joint: {p: 50.0, d: 0.0, i: 0.1, i_clamp: 0.5}
      wrist_1_joint: {p: 50.0, d: 0.0, i: 0.1, i_clamp: 0.5}
      wrist_2_joint: {p: 50.0, d: 0.0, i: 0.1, i_clamp: 0.5}
      wrist_3_joint: {p: 50.0, d: 0.0, i: 0.1, i_clamp: 0.5}
    ff_velocity_scale:
      shoulder_pan_joint: 0.1
      shoulder_lift_joint: 0.1
      elbow_joint: 0.1
      wrist_1_joint: 0.1
      wrist_2_joint: 0.1
      wrist_3_joint: 0.1
