action_client_joint_trajectory_controller_velocity:
  ros__parameters:

    controller_name: "velocity_trajectory_controller"
    wait_sec_between_publish: 15

    goal_names: ["pos1", "pos2", "pos3", "pos4", "pos5", "pos6"]
    pos1: [0.0, 0.0, -0.2, 0.0, 0.0, 0.0]
    pos2: [0.0, 0.0, 0.2, 0.0, 0.0, 0.0]
    pos3: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    pos4: [0.0, 0.0, 0.2, 0.0, 0.0, 0.0]
    pos5: [0.0, 0.0, -0.2, 0.0, 0.0, 0.0]
    pos6: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      shoulder_pan_joint: [-0.1,0.1]
      shoulder_lift_joint: [-0.1,0.1]
      elbow_joint: [-0.1,0.1]
      wrist_1_joint: [-0.1,0.1]
      wrist_2_joint: [-0.1,0.1]
      wrist_3_joint: [-0.1,0.1]